config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :comments
  end

  resources :users
	
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }
  
  resources :orders, only: [:index, :show, :create, :destroy]


  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  root 'static_pages#landing_page'

  post 'static_pages/thank_you'

  post 'payments/create'

  mount ActionCable.server => '/cable'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/static_pages/landing_page">Brand</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "About", static_pages_about_path %><span class="sr-only">(current)</span></li>
            <li><%= link_to "Contact", static_pages_contact_path %></li>
          </ul>

          <ul class="nav pull-right login">
            <% if user_signed_in? %>
            <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </li>
            <% else %>
            <li>
              <%= link_to('Login', new_user_session_path) %>
            </li>
            <% end %>
          </ul>

          <!-- Search form -->
          <%= form_tag("/products", method: "get", class: "navbar-form navbar-left") do %>
            <div class="form-group">
              <%= label_tag(:q, "Search for:", class: "sr-only") %>
              <%= text_field_tag(:q, nil, class: "form-control", placeholder: "Search") %>
            </div>
            <%= submit_tag("Find", class: "btn btn-default btn-default-transparent") %>
          <% end %>


            <!-- Devise actions -->
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Products", products_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <% if notice %>
      <div class="alert alert-info flash-bkgr" role="alert">
        <p id="notice" class="alert alert-info flash"><%= notice %></p>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger " role="alert">
        <p id="alert" class="alert alert-info flash"><%= alert %></p>
      </div>
    <% end %>

    <%= yield %>


    <footer>
      <div class="container-footer">
        &copy; 2016 Bike Berlin
      </div>
    </footer>
  </body>
</html>